sonar.projectKey=pdrollucas_euSindico-frontend
sonar.organization=pdrollucas
sonar.host.url=https://sonarcloud.io
sonar.sources=src
sonar.tests=src,cypress
sonar.test.inclusions=**/*.spec.ts,cypress/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info,cypress-coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
