// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using euSindico.Infrastructure.Persistence;

#nullable disable

namespace euSindico.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("euSindico.Domain.Entities.CodigoRedefinicaoSenha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("codigo_hash");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expira_em");

                    b.Property<DateTime?>("UsadoEm")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("usado_em");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "CodigoHash");

                    b.HasIndex("UsuarioId", "CriadoEm");

                    b.HasIndex("UsuarioId", "UsadoEm");

                    b.ToTable("codigos_redefinicao_senha", (string)null);
                });

            modelBuilder.Entity("euSindico.Domain.Entities.Compromisso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Concluido")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("concluido");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly>("DataCompromisso")
                        .HasColumnType("date")
                        .HasColumnName("data_compromisso");

                    b.Property<string>("Detalhes")
                        .HasColumnType("text")
                        .HasColumnName("detalhes");

                    b.Property<TimeOnly>("HorarioCompromisso")
                        .HasColumnType("time(6)")
                        .HasColumnName("horario_compromisso");

                    b.Property<string>("NomePrestadorServico")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nome_prestador_servico");

                    b.Property<int>("PredioId")
                        .HasColumnType("int")
                        .HasColumnName("predio_id");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("PredioId", "DataCompromisso", "HorarioCompromisso");

                    b.ToTable("compromissos", (string)null);
                });

            modelBuilder.Entity("euSindico.Domain.Entities.Documento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("criado_em");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nome_arquivo");

                    b.Property<int>("PredioId")
                        .HasColumnType("int")
                        .HasColumnName("predio_id");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("int")
                        .HasColumnName("tipo_documento_id");

                    b.Property<string>("UrlArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("url_arquivo");

                    b.HasKey("Id");

                    b.HasIndex("TipoDocumentoId");

                    b.HasIndex("PredioId", "TipoDocumentoId");

                    b.ToTable("documentos", (string)null);
                });

            modelBuilder.Entity("euSindico.Domain.Entities.Planejamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly?>("DataPlanejamento")
                        .HasColumnType("date")
                        .HasColumnName("data_planejamento");

                    b.Property<string>("Detalhes")
                        .HasColumnType("text")
                        .HasColumnName("detalhes");

                    b.Property<string>("NomePrestadorServico")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nome_prestador_servico");

                    b.Property<decimal?>("OrcamentoPrevisto")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("orcamento_previsto");

                    b.Property<int>("PredioId")
                        .HasColumnType("int")
                        .HasColumnName("predio_id");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("PredioId");

                    b.ToTable("planejamentos", (string)null);
                });

            modelBuilder.Entity("euSindico.Domain.Entities.Predio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("criado_em");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("endereco");

                    b.Property<bool>("Excluido")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("excluido");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("excluido_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nome");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Excluido");

                    b.ToTable("predios", (string)null);
                });

            modelBuilder.Entity("euSindico.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expira_em");

                    b.Property<DateTime?>("RevogadoEm")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("revogado_em");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("token_hash");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UsuarioId", "RevogadoEm");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("euSindico.Domain.Entities.Relatorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnoReferencia")
                        .HasColumnType("int")
                        .HasColumnName("ano_referencia");

                    b.Property<DateTime>("GeradoEm")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("gerado_em");

                    b.Property<int>("MesReferencia")
                        .HasColumnType("int")
                        .HasColumnName("mes_referencia");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nome_arquivo");

                    b.Property<int>("PredioId")
                        .HasColumnType("int")
                        .HasColumnName("predio_id");

                    b.Property<string>("UrlArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("url_arquivo");

                    b.HasKey("Id");

                    b.HasIndex("PredioId", "AnoReferencia", "MesReferencia");

                    b.ToTable("relatorios", (string)null);
                });

            modelBuilder.Entity("euSindico.Domain.Entities.TipoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("tipo_documento", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Atas"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Normas"
                        });
                });

            modelBuilder.Entity("euSindico.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nome");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("senha_hash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("euSindico.Domain.Entities.CodigoRedefinicaoSenha", b =>
                {
                    b.HasOne("euSindico.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("euSindico.Domain.Entities.Compromisso", b =>
                {
                    b.HasOne("euSindico.Domain.Entities.Predio", "Predio")
                        .WithMany("Compromissos")
                        .HasForeignKey("PredioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Predio");
                });

            modelBuilder.Entity("euSindico.Domain.Entities.Documento", b =>
                {
                    b.HasOne("euSindico.Domain.Entities.Predio", "Predio")
                        .WithMany("Documentos")
                        .HasForeignKey("PredioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("euSindico.Domain.Entities.TipoDocumento", "TipoDocumento")
                        .WithMany("Documentos")
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Predio");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("euSindico.Domain.Entities.Planejamento", b =>
                {
                    b.HasOne("euSindico.Domain.Entities.Predio", "Predio")
                        .WithMany("Planejamentos")
                        .HasForeignKey("PredioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Predio");
                });

            modelBuilder.Entity("euSindico.Domain.Entities.Predio", b =>
                {
                    b.HasOne("euSindico.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Predios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("euSindico.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("euSindico.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("euSindico.Domain.Entities.Relatorio", b =>
                {
                    b.HasOne("euSindico.Domain.Entities.Predio", "Predio")
                        .WithMany("Relatorios")
                        .HasForeignKey("PredioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Predio");
                });

            modelBuilder.Entity("euSindico.Domain.Entities.Predio", b =>
                {
                    b.Navigation("Compromissos");

                    b.Navigation("Documentos");

                    b.Navigation("Planejamentos");

                    b.Navigation("Relatorios");
                });

            modelBuilder.Entity("euSindico.Domain.Entities.TipoDocumento", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("euSindico.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Predios");
                });
#pragma warning restore 612, 618
        }
    }
}
